language: node_js

cache:
  - ~/.npm
  - node_modules

node_js: 12

git:
  depth: 3

script: 
  - yarn build

deploy:
  provider: pages
  edge: true   # Permite manejar el sistema de control, de versiones y como se accede
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: master

